### ISSUE TITLE
[Q]About the development

### ISSUE THREAD

**Issue by Incognito4nonymous** [Nemirtingas/android_device_samsung_grandprimevelte#1]
Came interested from XDA and just wondered if this is this still being worked on.
:)

**Comment by Nemirtingas** [comment]
Yes but in my private git.

**Comment by Incognito4nonymous** [comment]
Amazing ! Thanks a lot, lotsa guys count on you dude :smile:

**Comment by Nemirtingas** [comment]
Currently I'm stuck.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Incognito4nonymous** [comment]
Oh fi. But you got it working for Cyanogenmod now didn't you ?

**Comment by Nemirtingas** [comment]
What you mean ? It boots and works for los 12.1 13.0 14.1 but every rom has bugs.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Incognito4nonymous** [comment]
Now I'm wondering, which issue got you stuck ?

**Comment by Nemirtingas** [comment]
Any rom can't use hardware codecs. Los 14.1 is pretty stable but got display glitches. Los 13.0 is not very stable and reboots. Los 12.1 got random reboot

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Incognito4nonymous** [comment]
Display glitches ?
